
package bankloker;

import IrisRecog.GUI;
import IrisRecog.IrisRecog;
import javax.swing.JOptionPane;

/**
 *
 * @author Murali1
 */
public class Newuser extends javax.swing.JFrame {

    /** Creates new form Newuser */
    public Newuser() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        nac = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        pin = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        mob = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        ema = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        cit = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        ad = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        pan = new javax.swing.JTextField();
        se = new javax.swing.JComboBox();
        jLabel10 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        hid = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(153, 51, 255));
        jPanel1.setForeground(new java.awt.Color(153, 0, 255));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 255, 0));
        jLabel1.setText("USER VERIFICATION");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(30, 30, 410, 42);

        jButton1.setBackground(new java.awt.Color(204, 255, 204));
        jButton1.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(51, 204, 255));
        jButton1.setText("GO TO IRISRECOGNITION");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(20, 450, 380, 37);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 51));
        jLabel3.setText("Account_No");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(90, 360, 130, 28);

        nac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nacActionPerformed(evt);
            }
        });
        jPanel1.add(nac);
        nac.setBounds(258, 350, 190, 30);

        jLabel2.setBackground(new java.awt.Color(255, 255, 0));
        jLabel2.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 51));
        jLabel2.setText("Pin_No");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(90, 400, 120, 30);
        jPanel1.add(pin);
        pin.setBounds(258, 390, 190, 30);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 51));
        jLabel4.setText("Mobile No");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(90, 280, 140, 28);

        mob.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mobActionPerformed(evt);
            }
        });
        jPanel1.add(mob);
        mob.setBounds(258, 270, 190, 30);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 102));
        jLabel5.setText("Email");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(90, 110, 110, 28);

        ema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emaActionPerformed(evt);
            }
        });
        jPanel1.add(ema);
        ema.setBounds(258, 110, 190, 30);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 51));
        jLabel6.setText("City");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(90, 240, 60, 30);
        jPanel1.add(cit);
        cit.setBounds(258, 230, 190, 30);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 51));
        jLabel7.setText("Address");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(90, 200, 90, 28);

        ad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adActionPerformed(evt);
            }
        });
        jPanel1.add(ad);
        ad.setBounds(258, 190, 190, 30);

        jLabel8.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 102));
        jLabel8.setText("Sex");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(90, 160, 50, 20);

        jLabel9.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 102));
        jLabel9.setText("PAN No");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(90, 320, 100, 30);
        jPanel1.add(pan);
        pan.setBounds(258, 310, 190, 30);

        se.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Male", "Female" }));
        jPanel1.add(se);
        se.setBounds(258, 150, 190, 30);
        jPanel1.add(jLabel10);
        jLabel10.setBounds(0, 0, 570, 510);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bankloker/Back_1.jpg"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(430, 450, 120, 30);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bankloker/Eye4.jpg"))); // NOI18N
        jPanel1.add(jLabel11);
        jLabel11.setBounds(0, 0, 710, 510);

        hid.setBackground(new java.awt.Color(153, 0, 255));
        hid.setEditable(false);
        hid.setForeground(new java.awt.Color(153, 0, 255));
        hid.setText("newuser");
        hid.setCaretColor(new java.awt.Color(153, 0, 255));
        hid.setDisabledTextColor(new java.awt.Color(153, 0, 255));
        hid.setEnabled(false);
        hid.setSelectedTextColor(new java.awt.Color(153, 0, 204));
        hid.setSelectionColor(new java.awt.Color(153, 0, 255));
        hid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hidActionPerformed(evt);
            }
        });
        jPanel1.add(hid);
        hid.setBounds(230, 50, 250, 20);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 557, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 509, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

         if(  ema.getText().isEmpty()  )
        {
            JOptionPane.showMessageDialog(null, "Enter Email Id");
            
        }
         else if( ad.getText().isEmpty() )
        {
            JOptionPane.showMessageDialog(null, "Enter Address");
          
        }
          else if(  cit.getText().isEmpty() )
 {
     JOptionPane.showMessageDialog(null, "Enter City");
     
 }
         else if( mob.getText().isEmpty() )
 {
     JOptionPane.showMessageDialog(null, "Enter Mobile number");
    
 }
         else if(  pan.getText().isEmpty()  )
 {
     JOptionPane.showMessageDialog(null, "Enter Pan card Number");
      
 } 
        
         else if ( (!ema.getText().contains("@"))|| (!ema.getText().contains(".")) )
    {
        JOptionPane.showMessageDialog(null, "Enter Proper Email-id with @ & .(dot)");
       // JOptionPane.showMessageDialog(null, "Enter 10 digit Account number,4 digit pin number,Enter Proper Email-id and also dont left empty fields");
            
    } 
         else if( nac.getText().length() != 10 )
 {
     JOptionPane.showMessageDialog(null, "Enter 10 digit Account number");
   
 }
         else if(  pin.getPassword().length != 4  )
 {
     JOptionPane.showMessageDialog(null, "Enter 4 digit pin number");
     
 }
    
   
  
else
         {
             GUI gui_View = new GUI();

		IrisRecog irg_Model = new IrisRecog(gui_View);

		gui_View.setModel(irg_Model);
       
         }

  


   
    
}//GEN-LAST:event_jButton1ActionPerformed

private void hidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hidActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_hidActionPerformed

private void mobActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mobActionPerformed
    // TODO add your handling code here:
}//GEN-LAST:event_mobActionPerformed

private void emaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emaActionPerformed
    // TODO add your handling code here:
}//GEN-LAST:event_emaActionPerformed

private void adActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adActionPerformed
    // TODO add your handling code here:
}//GEN-LAST:event_adActionPerformed

private void nacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nacActionPerformed
    // TODO add your handling code here:
}//GEN-LAST:event_nacActionPerformed

private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    // TODO add your handling code here:
     Home1 nf=   new Home1();
     nf.setVisible(true);
             this.setVisible(false);
}//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Newuser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Newuser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Newuser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Newuser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
              
                new Newuser().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JTextField ad;
    public static javax.swing.JTextField cit;
    public static javax.swing.JTextField ema;
    public static javax.swing.JTextField hid;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    public static javax.swing.JTextField mob;
    public static javax.swing.JTextField nac;
    public static javax.swing.JTextField pan;
    public static javax.swing.JPasswordField pin;
    public static javax.swing.JComboBox se;
    // End of variables declaration//GEN-END:variables
}
